### ISSUE TITLE
Power BI Sample Reports 

### ISSUE THREAD

**Issue by barryschulz** [microsoft/PowerBI-Embedded-Showcases#2]
Are the reports available that are referenced by the samples? 

For example, is the report referenced below available for download? 

ReportId: 85775f96-3b31-45ce-a1d5-bdcbf11e47c4
https://playground.powerbi.com/en-us/showcases-gallery/quick-visual-creator

**Comment by v-MadhavC** [comment]
The reports referenced in the samples are not available for download. You can view and interact with them in the Power BI Playground.
