### ISSUE TITLE
How to change page layout with parameters on ReportEmbed URL?

### ISSUE THREAD

**Issue by luissimoesneom** [microsoft/PowerBI-Embedded-Showcases#6]
Is there any way to change to FitToPage or FitToWidth when embeding using the ReportEmbed URL?

Thank you

**Comment by v-MadhavC** [comment]
To change the layout, modify the embed configuration by specifying FitToWidth in the custom layout settings. You can set it to FitToWidth, FitToPage, or ActualPage as needed.
![Image](https://github.com/user-attachments/assets/0652c4fb-8fae-42ef-aa2b-3af1ea26e9f3)
