### ISSUE TITLE
change the report it refers to

### ISSUE THREAD

**Issue by peya02** [microsoft/PowerBI-Embedded-Showcases#7]
Sorry,
How can I change the report it refers to?

**Comment by v-MadhavC** [comment]
Power BI Playground Showcases do not support changing the report reference directly. To change the report reference, you'll need to update the embedConfig object in the code by providing the new accessToken, embedUrl, and reportId.

To generate the access token, use the following REST API: [Embed Token - Generate Token - REST API (Power BI Power BI REST APIs) | Microsoft Learn](https://learn.microsoft.com/en-us/rest/api/power-bi/embed-token/generate-token)

To generate the embed token, use the following REST API: [Reports - Get Report In Group - REST API (Power BI Power BI REST APIs) | Microsoft Learn](https://learn.microsoft.com/en-us/rest/api/power-bi/reports/get-report-in-group?tryIt=true&source=docs#code-try-0)
