### ISSUE TITLE
Customize Fonts 

### ISSUE THREAD

**Issue by mauroruffinocsi** [microsoft/PowerBI-Embedded-Showcases#9]
is there a way to customize font type from playground ? i see color customization but nothing about fonts.

it s not so good for an embedding platform that font works only if locally installed on user's pc used to view the embedding visual object....

**Comment by v-MadhavC** [comment]
Thank you for reporting this issue. This is a feature request, please add it in the following link where we can collect votes: https://ideas.fabric.microsoft.com . If the feature is already there, you can add a vote.
